---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-scheduler
  namespace: hermes
spec:
  selector:
    matchLabels:
      app: hermes-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: hermes-scheduler
    spec:
      containers:
      - name: hermes-scheduler
        image: rdkr/hermes-scheduler:latest
        imagePullPolicy: Always
        command:
          - python
        args:
          - main.py
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_DISCORD_TOKEN
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: hermes
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: hermes
                key: AWS_SECRET_ACCESS_KEY
          - name: DB_USER
            value: postgres
          - name: DB_HOST
            value: postgres-postgresql.hermes.svc.cluster.local
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: postgres-postgresql
                key: postgresql-password
