"""mark dc ids as unique

Revision ID: 7d2fd032a113
Revises: ca0b2f8ea6cc
Create Date: 2020-06-22 19:45:00.710716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d2fd032a113"
down_revision = "ca0b2f8ea6cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "events", ["event_dc_id"])
    op.create_unique_constraint(None, "players", ["player_dc_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "players", type_="unique")
    op.drop_constraint(None, "events", type_="unique")
    # ### end Alembic commands ###
