"""init

Revision ID: ca0b2f8ea6cc
Revises: 
Create Date: 2020-06-22 19:28:14.618270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0b2f8ea6cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_dc_id', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('min_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_dc_id', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('player_tz', sa.String(), nullable=False),
    sa.Column('magic_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('magic_token')
    )
    op.create_table('timeranges',
    sa.Column('timerange_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('timerange_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeranges')
    op.drop_table('players')
    op.drop_table('events')
    # ### end Alembic commands ###
