"""time/players not req for event

Revision ID: eab04170cfab
Revises: 4e9b9a49141b
Create Date: 2020-06-23 00:36:58.689506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eab04170cfab'
down_revision = '4e9b9a49141b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'min_players',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'min_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'min_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('events', 'min_players',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
